### ISSUE TITLE
Error when generating seo title (Neos.Seo:TitleTagMixin)

### ISSUE THREAD

**Issue by rtp-cgs** [NEOSidekick/NEOSidekick.AiAssistant#13] opened 2024-05-29 13:50 UTC
When I try to generate the seo title (Title override) using the new "Generate with Sidekick" button, I get the following error in a flash message:
An error occurred while asking NEOSidekick: The given data was invalid.

Here is the request and response from the ajax call:

**Request & payload:**
https://api.neosidekick.com/api/v1/chat?language=de
```
{"module":"seo_title","platform":"neos","user_input":[{"identifier":"url","value":"home"},
{"identifier":"focusKeyword","value":"Websites"},{"identifier":"content","value":"..."}}
```

**Response:**
```
{
    "errors": {
        "module": [
            "The module 'seo_title' is invalid. The available modules are: alt_tag_generator, blogpost_ideas, chameleon_solutions_generator, chat_conversation, content_improver, content_structure, custom_prompt, faq_generator, focus_keyword_generator, free_conversation, free_conversation_with_function_call, full_seo_article_generation, image_alt_text, keyword_research, linked_in_share_message, meta_description, meta_description_three_suggestions, modify_selected_text, online_research, page_conclusion_writer, page_title_writer, paragraph_generation, puls24_article_summarizer, read_the_following, site_briefing, summarize_in_one_paragraph, text_correction, text_improver, translation"
        ]
    },
    "message": "The given data was invalid."
}
```

**Screenshot:**
![CleanShot 2024-05-29 at 16 02 46@2x](https://github.com/NEOSidekick/NEOSidekick.AiAssistant/assets/59559730/f73caa37-8c89-4835-91c3-4bce3667a296)

**Package Versions:**
neosidekick/ai-assistant: v2.2.1
neos/neos: 8.3.12

**Comment by rolandschuetz** [comment] 2024-06-02 17:54
@rtp-cgs Thanks for the great bug report, the issue is fixed on the server. We had changed the module name and forgot to push that to production.

**Closed as completed** 2024-06-02 17:54 UTC
